### ISSUE TITLE
Misplaced hot spot on some diagonal resize cursors

### ISSUE THREAD

**Issue by mjoork** [Notify-ctrl/Plasma-Overdose#1]
Some diagonal resize cursors (NE, SW) have misplaced hot spot I believe.

![NE](https://user-images.githubusercontent.com/20644474/152822607-3419bb9b-85f1-4c88-bdfa-d120bc056a08.png)
![SW](https://user-images.githubusercontent.com/20644474/152822610-e934e60a-c8df-4ce7-9ece-3498ac16f761.png)
.

**Comment by Notify-ctrl** [comment]
Thanks for your issue. Now their hot spots are corrent now, please update your cursors.😃
